# Generated by Django 5.2.5 on 2025-08-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCliente', models.CharField(choices=[('persona_fisica', 'Persona Física'), ('persona_juridica', 'Persona Jurídica')], max_length=50, verbose_name='Tipo de Cliente')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('razonSocial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('categoria', models.CharField(choices=[('mino', 'Minorista'), ('corp', 'Corporativo'), ('vip', 'VIP')], default='mino', max_length=50, verbose_name='Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fechaRegistro'],
            },
        ),
    ]
