# Generated by Django 5.2.5 on 2025-09-15 11:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre de la categoría')),
                ('descuento', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('base_price', models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Precio Base')),
                ('comision_venta', models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Comisión por venta')),
                ('comision_compra', models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Comisión por compra')),
                ('decimales_cotizacion', models.PositiveSmallIntegerField(default=4, help_text='Número de decimales para mostrar y almacenar la tasa de cambio (0-8)', verbose_name='Decimales para tasa de cambio')),
                ('decimales_monto', models.PositiveSmallIntegerField(default=2, help_text='Número de decimales para mostrar y almacenar los montos (0-8)', verbose_name='Decimales para montos')),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='currency_flags/', verbose_name='Bandera (255x135)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCliente', models.CharField(choices=[('persona_fisica', 'Persona Física'), ('persona_juridica', 'Persona Jurídica')], max_length=50, verbose_name='Tipo de Cliente')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('razonSocial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='webapp.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fechaRegistro'],
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta de Débito/Crédito'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('cheque', 'Cheque')], max_length=20, verbose_name='Tipo de Medio de Pago')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Medio de Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='webapp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medios_pago',
                'ordering': ['cliente__nombre', 'tipo', 'nombre'],
                'unique_together': {('cliente', 'tipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('alias_cbu', models.CharField(max_length=50, verbose_name='Alias/CBU')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuentas_bancarias',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, verbose_name='Número de Cheque')),
                ('banco_emisor', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'db_table': 'cheques',
            },
        ),
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', models.CharField(max_length=20, verbose_name='Número de Celular')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'db_table': 'billeteras',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tokenizado', models.CharField(help_text='Número de tarjeta encriptado/tokenizado', max_length=50, verbose_name='Número Tokenizado')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('ultimos_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjetas',
            },
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente-Usuario',
                'verbose_name_plural': 'Clientes-Usuarios',
                'db_table': 'cliente_usuario',
                'unique_together': {('cliente', 'usuario')},
            },
        ),
    ]
