# Generated by Django 5.2.5 on 2025-08-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
    ]
