# Generated by Django 5.2.5 on 2025-09-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Pago')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio Compra')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio Venta')),
                ('effective_date', models.DateField(verbose_name='Fecha Vigencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.currency', verbose_name='Moneda')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.paymenttype', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'unique_together': {('currency', 'payment_type', 'effective_date')},
            },
        ),
    ]
