# Generated by Django 5.2.5 on 2025-09-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCliente', models.CharField(choices=[('persona_fisica', 'Persona Física'), ('persona_juridica', 'Persona Jurídica')], max_length=50, verbose_name='Tipo de Cliente')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('razonSocial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('categoria', models.CharField(choices=[('mino', 'Minorista'), ('corp', 'Corporativo'), ('vip', 'VIP')], default='mino', max_length=50, verbose_name='Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fechaRegistro'],
            },
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente-Usuario',
                'verbose_name_plural': 'Clientes-Usuarios',
                'db_table': 'cliente_usuario',
                'unique_together': {('cliente', 'usuario')},
            },
        ),
    ]
