# Generated by Django 5.2.5 on 2025-09-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cliente_clienteusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='buy_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tasa de compra'),
        ),
        migrations.AddField(
            model_name='currency',
            name='sell_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tasa de venta'),
        ),
    ]
