# Generated by Django 5.2.5 on 2025-09-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_currency_buy_rate_currency_sell_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='currency_flags/', verbose_name='Bandera (255x135)'),
        ),
    ]
