# Generated by Django 5.2.5 on 2025-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_currency_exchange_rate_currency_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='decimales_cotizacion',
            field=models.PositiveSmallIntegerField(default=4, help_text='Número de decimales para mostrar y almacenar la tasa de cambio (0-8)', verbose_name='Decimales para tasa de cambio'),
        ),
        migrations.AddField(
            model_name='currency',
            name='decimales_monto',
            field=models.PositiveSmallIntegerField(default=2, help_text='Número de decimales para mostrar y almacenar los montos (0-8)', verbose_name='Decimales para montos'),
        ),
    ]
