# Generated by Django 5.2.5 on 2025-09-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_currency_decimales_cotizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy_rate',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Tasa de compra'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell_rate',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Tasa de venta'),
        ),
    ]
