# Generated by Django 5.2.5 on 2025-09-15 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


def create_categorias_and_migrate_data(apps, schema_editor):
    """
    Crea las categorías y migra los datos existentes
    """
    Cliente = apps.get_model("webapp", "Cliente")
    Categoria = apps.get_model("webapp", "Categoria")
    
    # Crear las categorías por defecto
    categorias_data = [
        {"nombre": "VIP", "descuento": 0.000},
        {"nombre": "Minorista", "descuento": 0.000},
        {"nombre": "Corporativo", "descuento": 0.000},
    ]
    
    categoria_objects = {}
    for cat_data in categorias_data:
        categoria, created = Categoria.objects.get_or_create(
            nombre=cat_data["nombre"], 
            defaults={"descuento": cat_data["descuento"]}
        )
        categoria_objects[cat_data["nombre"]] = categoria
    
    # Mapeo de valores antiguos a nombres de categorías
    categoria_mapping = {
        'mino': categoria_objects['Minorista'],
        'corp': categoria_objects['Corporativo'], 
        'vip': categoria_objects['VIP']
    }
    
    # Migrar cada cliente
    for cliente in Cliente.objects.all():
        if hasattr(cliente, 'categoria') and cliente.categoria in categoria_mapping:
            cliente.categoria_new = categoria_mapping[cliente.categoria]
            cliente.save()


def reverse_migrate_data(apps, schema_editor):
    """
    Revierte la migración
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_currency_buy_rate_alter_currency_sell_rate'),
    ]

    operations = [
        # Crear la tabla Categoria
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre de la categoría')),
                ('descuento', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        
        # Agregar la nueva columna categoria_new como nullable
        migrations.AddField(
            model_name='cliente',
            name='categoria_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='webapp.categoria', verbose_name='Categoría'),
        ),
        
        # Migrar los datos
        migrations.RunPython(create_categorias_and_migrate_data, reverse_migrate_data),
        
        # Hacer la columna no nullable
        migrations.AlterField(
            model_name='cliente',
            name='categoria_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='webapp.categoria', verbose_name='Categoría'),
        ),
        
        # Eliminar la columna antigua
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
        
        # Renombrar la nueva columna
        migrations.RenameField(
            model_name='cliente',
            old_name='categoria_new',
            new_name='categoria',
        ),
    ]
