# Generated by Django 5.2.5 on 2025-09-13 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def crear_categorias(apps, schema_editor):
    Categoria = apps.get_model("webapp", "Categoria")
    categorias_default = [
        {"nombre": "VIP", "descuento": 0.000},
        {"nombre": "Minorista", "descuento": 0.000},
        {"nombre": "Corporativo", "descuento": 0.000},
    ]
    for cat in categorias_default:
        Categoria.objects.get_or_create(nombre=cat["nombre"], defaults={"descuento": cat["descuento"]})

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_currency_buy_rate_alter_currency_sell_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre de la categoría')),
                ('descuento', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='webapp.categoria', verbose_name='Categoría'),
        ),
        migrations.RunPython(crear_categorias),
    ]
