# Generated by Django 5.2.5 on 2025-09-15 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20250915_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('billetera', 'Billetera'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque')], max_length=20, unique=True, verbose_name='Tipo de Medio de Pago')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medios_pago',
                'ordering': ['tipo'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.CreateModel(
            name='ClienteMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='webapp.cliente', verbose_name='Cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Cliente-Medio de Pago',
                'verbose_name_plural': 'Clientes-Medios de Pago',
                'db_table': 'cliente_medio_pago',
                'ordering': ['cliente__nombre', 'medio_pago__nombre'],
                'unique_together': {('cliente', 'medio_pago')},
            },
        ),
    ]
