# Generated by Django 5.2.5 on 2025-09-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_mediopago_alter_categoria_options_clientemediopago'),
    ]

    operations = [
        # Eliminar tablas existentes
        migrations.RunSQL(
            "DROP TABLE IF EXISTS cliente_medio_pago CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS medios_pago CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Recrear tabla medios_pago con nueva estructura
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta de Débito/Crédito'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('cheque', 'Cheque')], max_length=20, verbose_name='Tipo de Medio de Pago')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Medio de Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='webapp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medios_pago',
                'ordering': ['cliente__nombre', 'tipo', 'nombre'],
            },
        ),
        
        # Crear tabla tarjetas
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tokenizado', models.CharField(help_text='Número de tarjeta encriptado/tokenizado', max_length=50, verbose_name='Número Tokenizado')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('ultimos_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjetas',
            },
        ),
        
        # Crear tabla billeteras
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', models.CharField(max_length=20, verbose_name='Número de Celular')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'db_table': 'billeteras',
            },
        ),
        
        # Crear tabla cuentas_bancarias
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('alias_cbu', models.CharField(max_length=50, verbose_name='Alias/CBU')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuentas_bancarias',
            },
        ),
        
        # Crear tabla cheques
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, verbose_name='Número de Cheque')),
                ('banco_emisor', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='webapp.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'db_table': 'cheques',
            },
        ),
        
        # Agregar constraint unique_together
        migrations.AlterUniqueTogether(
            name='mediopago',
            unique_together={('cliente', 'tipo', 'nombre')},
        ),
    ]
