# Generated by Django 5.2.5 on 2025-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_recreate_payment_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='buy_rate',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='sell_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='base_price',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Precio Base'),
        ),
        migrations.AddField(
            model_name='currency',
            name='comision_compra',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Comisión por compra'),
        ),
        migrations.AddField(
            model_name='currency',
            name='comision_venta',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=23, verbose_name='Comisión por venta'),
        ),
    ]
