# Generated by Django 5.2.5 on 2025-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_currency_buy_rate_remove_currency_sell_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('billetera', 'Billetera'), ('cheque', 'Cheque'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('tarjeta', 'Tarjeta')], max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)')),
            ],
            options={
                'verbose_name': 'Configuración de Medio de Pago',
                'verbose_name_plural': 'Configuraciones de Medios de Pago',
                'db_table': 'tipo_medio_pago_config',
            },
        ),
    ]
