# Generated by Django 5.2.5 on 2025-09-16 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_tipopago_delete_tipomediopagoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, help_text='Configuración global de activación y comisión', null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tipopago', verbose_name='Tipo de Pago Global'),
        ),
    ]
