# Generated by Django 5.2.5 on 2025-09-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_mediopago_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo_guaranies', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto mínimo (Gs)')),
                ('maximo_guaranies', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto máximo (Gs)')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite', to='webapp.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Límite por Categoría',
                'verbose_name_plural': 'Límites por Categoría',
            },
        ),
    ]
