# Generated by Django 5.2.5 on 2025-09-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_limitecategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitecategoria',
            name='maximo_guaranies',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Monto máximo (Gs)'),
        ),
        migrations.AlterField(
            model_name='limitecategoria',
            name='minimo_guaranies',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Monto mínimo (Gs)'),
        ),
    ]
