# Generated by Django 5.2.5 on 2025-09-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_limitecategoria_maximo_guaranies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCategoriaMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto mínimo')),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto máximo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_categoria', to='webapp.categoria')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_moneda', to='webapp.currency')),
            ],
            options={
                'verbose_name': 'Límite de Intercambio',
                'verbose_name_plural': 'Límites de Intercambio',
                'unique_together': {('categoria', 'moneda')},
            },
        ),
        migrations.DeleteModel(
            name='LimiteCategoria',
        ),
    ]
