# Generated by Django 5.2.5 on 2025-09-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_limitecategoriamoneda_delete_limitecategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteIntercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_min', models.DecimalField(decimal_places=2, max_digits=23, verbose_name='Monto Mínimo')),
                ('monto_max', models.DecimalField(decimal_places=2, max_digits=23, verbose_name='Monto Máximo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_intercambio', to='webapp.categoria', verbose_name='Categoría de Cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_intercambio', to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Límite de Intercambio',
                'verbose_name_plural': 'Límites de Intercambio',
                'ordering': ['moneda__code', 'categoria__nombre'],
                'unique_together': {('moneda', 'categoria')},
            },
        ),
        migrations.DeleteModel(
            name='LimiteCategoriaMoneda',
        ),
    ]
