# Generated by Django 5.2.5 on 2025-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_limiteintercambio_delete_limitecategoriamoneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteintercambio',
            name='monto_max',
            field=models.DecimalField(decimal_places=8, error_messages={'max_decimal_places': 'El número no puede tener más de 8 decimales', 'max_digits': 'El número no puede tener más de 23 dígitos'}, max_digits=23, verbose_name='Monto Máximo'),
        ),
        migrations.AlterField(
            model_name='limiteintercambio',
            name='monto_min',
            field=models.DecimalField(decimal_places=8, error_messages={'max_decimal_places': 'El número no puede tener más de 8 decimales', 'max_digits': 'El número no puede tener más de 23 dígitos'}, max_digits=23, verbose_name='Monto Mínimo'),
        ),
    ]
