# Generated by Django 5.2.5 on 2025-09-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_mediopago_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediopago',
            name='moneda',
        ),
        migrations.AddField(
            model_name='billetera',
            name='moneda',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='moneda',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='moneda',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
    ]
