# Generated by Django 5.2.5 on 2025-09-19 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_mediopago_moneda_billetera_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='moneda',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
    ]
