# Generated by Django 5.2.5 on 2025-09-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_mediopago_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
    ]
