# Generated by Django 5.2.5 on 2025-09-20 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_mediopago_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta de Débito/Crédito'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('cheque', 'Cheque')], max_length=20, verbose_name='Tipo de Método de Cobro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Método de Cobro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_cobro', to='webapp.cliente', verbose_name='Cliente')),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
                ('tipo_cobro', models.ForeignKey(blank=True, help_text='Configuración global de activación y comisión', null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tipopago', verbose_name='Tipo de Cobro Global')),
            ],
            options={
                'verbose_name': 'Método de Cobro',
                'verbose_name_plural': 'Métodos de Cobro',
                'db_table': 'medios_cobro',
                'ordering': ['cliente__nombre', 'tipo', 'nombre'],
                'unique_together': {('cliente', 'tipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('alias_cbu', models.CharField(max_length=50, verbose_name='Alias/CBU')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
                ('medio_cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria_cobro', to='webapp.mediocobro', verbose_name='Método de Cobro')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria de Cobro',
                'verbose_name_plural': 'Cuentas Bancarias de Cobro',
                'db_table': 'cuentas_bancarias_cobro',
            },
        ),
        migrations.CreateModel(
            name='ChequeCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, verbose_name='Número de Cheque')),
                ('banco_emisor', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
                ('medio_cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_cobro', to='webapp.mediocobro', verbose_name='Método de Cobro')),
            ],
            options={
                'verbose_name': 'Cheque de Cobro',
                'verbose_name_plural': 'Cheques de Cobro',
                'db_table': 'cheques_cobro',
            },
        ),
        migrations.CreateModel(
            name='BilleteraCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', models.CharField(max_length=20, verbose_name='Número de Celular')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
                ('medio_cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera_cobro', to='webapp.mediocobro', verbose_name='Método de Cobro')),
            ],
            options={
                'verbose_name': 'Billetera de Cobro',
                'verbose_name_plural': 'Billeteras de Cobro',
                'db_table': 'billeteras_cobro',
            },
        ),
        migrations.CreateModel(
            name='TarjetaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tokenizado', models.CharField(help_text='Número de tarjeta encriptado/tokenizado', max_length=50, verbose_name='Número Tokenizado')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('ultimos_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('medio_cobro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_cobro', to='webapp.mediocobro', verbose_name='Método de Cobro')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tarjeta de Cobro',
                'verbose_name_plural': 'Tarjetas de Cobro',
                'db_table': 'tarjetas_cobro',
            },
        ),
    ]
