# Generated by Django 5.2.5 on 2025-09-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_mediocobro_cuentabancariacobro_chequecobro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo de Cobro',
                'verbose_name_plural': 'Tipos de Cobro',
            },
        ),
    ]
