# Generated by Django 5.2.5 on 2025-09-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_tipocobro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_admin_panel', 'Can access admin panel')]},
        ),
    ]
