# Generated by Django 5.2.5 on 2025-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('telefono', 'Entidad Telefónica')], max_length=20, verbose_name='Tipo de Entidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entidades',
            },
        ),
        migrations.RemoveField(
            model_name='billetera',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='billeteracobro',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='banco_emisor',
        ),
        migrations.RemoveField(
            model_name='chequecobro',
            name='banco_emisor',
        ),
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cuentabancariacobro',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='tarjetacobro',
            name='banco',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tokenizado',
            field=models.CharField(max_length=50, verbose_name='Número Tokenizado'),
        ),
        migrations.AlterField(
            model_name='tarjetacobro',
            name='numero_tokenizado',
            field=models.CharField(max_length=50, verbose_name='Número Tokenizado'),
        ),
    ]
