# Generated by Django 5.2.5 on 2025-09-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_entidad_remove_billetera_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetera',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'telefono'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='billeteracobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'telefono'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
        migrations.AddField(
            model_name='chequecobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='cuentabancariacobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
        migrations.AddField(
            model_name='tarjetacobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
    ]
