# Generated by Django 5.2.5 on 2025-09-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_add_generic_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'telefono'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='billeteracobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'telefono'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
        migrations.AlterField(
            model_name='chequecobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='cuentabancariacobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='tarjetacobro',
            name='entidad',
            field=models.ForeignKey(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor'),
        ),
    ]
