# Generated by Django 5.2.5 on 2025-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_alter_billetera_entidad_alter_billeteracobro_entidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequecobro',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='chequecobro',
            name='medio_cobro',
        ),
        migrations.RemoveField(
            model_name='chequecobro',
            name='moneda',
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Débito/Crédito'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria')], max_length=20, verbose_name='Tipo de Método de Cobro'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Débito/Crédito'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria')], max_length=20, verbose_name='Tipo de Medio de Pago'),
        ),
        migrations.DeleteModel(
            name='Cheque',
        ),
        migrations.DeleteModel(
            name='ChequeCobro',
        ),
    ]
