# Generated by Django 5.2.5 on 2025-09-23 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_remove_chequecobro_entidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limiteintercambio',
            options={'ordering': ['moneda__code'], 'verbose_name': 'Límite de Intercambio', 'verbose_name_plural': 'Límites de Intercambio'},
        ),
        migrations.AlterUniqueTogether(
            name='limiteintercambio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='limiteintercambio',
            name='limite_dia',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), error_messages={'max_decimal_places': 'El número no puede tener más de 8 decimales', 'max_digits': 'El número no puede tener más de 23 dígitos'}, max_digits=23, verbose_name='Límite Diario'),
        ),
        migrations.AddField(
            model_name='limiteintercambio',
            name='limite_mes',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), error_messages={'max_decimal_places': 'El número no puede tener más de 8 decimales', 'max_digits': 'El número no puede tener más de 23 dígitos'}, max_digits=23, verbose_name='Límite Mensual'),
        ),
        migrations.RemoveField(
            model_name='limiteintercambio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='limiteintercambio',
            name='monto_max',
        ),
        migrations.RemoveField(
            model_name='limiteintercambio',
            name='monto_min',
        ),
    ]
