# Generated by Django 5.2.5 on 2025-09-23 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_alter_limiteintercambio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=8, max_digits=23, verbose_name='Monto Origen')),
                ('monto_destino', models.DecimalField(blank=True, decimal_places=8, max_digits=23, null=True, verbose_name='Monto Destino')),
                ('tasa_cambio', models.DecimalField(decimal_places=8, help_text='Incluye comisiones aplicadas', max_digits=23, verbose_name='Tasa de Cambio')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones', to='webapp.cliente', verbose_name='Cliente')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_destino', to='webapp.currency', verbose_name='Moneda Destino')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_origen', to='webapp.currency', verbose_name='Moneda Origen')),
            ],
            options={
                'verbose_name': 'Conversión',
                'verbose_name_plural': 'Conversiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
