# Generated by Django 5.2.5 on 2025-09-23 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0033_alter_limiteintercambio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timbrado', models.IntegerField()),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='emitida', max_length=20)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cliente')),
                ('detalleFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.detallefactura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=15)),
                ('medio_pago_id', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='webapp.cliente')),
                ('factura_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='webapp.factura')),
                ('medio_pago_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='webapp.currency')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='webapp.currency')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.transaccion'),
        ),
    ]
