# Generated by Django 5.2.5 on 2025-09-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0034_detallefactura_factura_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='medio_cobro_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_cobro_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_cobro', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='medio_pago_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_pago', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_destino',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_origen',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
