# Generated by Django 5.2.5 on 2025-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_transaccion_medio_cobro_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='entidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('banco', 'Banco'), ('telefono', 'Teléfono')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='entidad',
            table=None,
        ),
    ]
