# Generated by Django 5.2.5 on 2025-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_alter_entidad_options_alter_entidad_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('banco', 'Banco'), ('telefono', 'Entidad Telefónica')], max_length=20),
        ),
    ]
