# Generated by Django 5.2.5 on 2025-09-25 21:10

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_entidad_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tipo_cobro', models.ForeignKey(blank=True, help_text='Configuración global de activación y comisión', null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tipocobro', verbose_name='Tipo de Cobro Global')),
                ('tipo_pago', models.ForeignKey(blank=True, help_text='Configuración global de activación y comisión', null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tipopago', verbose_name='Tipo de Pago Global')),
            ],
            options={
                'verbose_name': 'Tauser',
                'verbose_name_plural': 'Tausers',
                'db_table': 'tauser',
            },
        ),
    ]
