# Generated by Django 5.2.5 on 2025-09-26 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_entidad_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la cotización')),
                ('compra', models.DecimalField(decimal_places=8, max_digits=23, verbose_name='Tasa de compra')),
                ('venta', models.DecimalField(decimal_places=8, max_digits=23, verbose_name='Tasa de venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='webapp.currency')),
            ],
            options={
                'verbose_name': 'Histórico de moneda',
                'verbose_name_plural': 'Históricos de monedas',
                'ordering': ['-date', 'currency'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
