# Generated by Django 5.2.5 on 2025-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_currencyhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='limiteintercambio',
            unique_together={('moneda',)},
        ),
    ]
