# Generated by Django 5.2.5 on 2025-09-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_add_generic_tausers'),
        ('webapp', '0039_alter_limiteintercambio_unique_together'),
    ]

    operations = [
    ]
