# Generated by Django 5.2.5 on 2025-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_currencyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('custom', 'Personalizado')], default='daily', max_length=20)),
                ('hour', models.IntegerField(default=8)),
                ('minute', models.IntegerField(default=0)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
