# Generated by Django 5.2.5 on 2025-09-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_emailscheduleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_exchange_emails',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones de tasas de cambio'),
        ),
    ]
