# Generated by Django 5.2.5 on 2025-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_customuser_receive_exchange_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
