# Generated by Django 5.2.5 on 2025-10-09 04:12

from django.db import migrations

def eliminar_registros(apps, schema_editor):
    TipoCobro = apps.get_model('webapp', 'TipoCobro')
    TipoPago = apps.get_model('webapp', 'TipoPago')

    # Eliminar el registro "Tarjeta" de TipoCobro
    TipoCobro.objects.filter(nombre="Tarjeta").delete()

    # Eliminar el registro "Cuenta_bancaria" de TipoPago
    TipoPago.objects.filter(nombre="Cuenta Bancaria").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_assign_tipo_pago_cobro_to_existing_tausers'),
    ]

    operations = [
        migrations.RunPython(eliminar_registros),
    ]
