# Generated by Django 5.2.5 on 2025-10-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_remover_filas_de_tipocobro_tipopago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarjetaCobro',
        ),
    ]
