# Generated by Django 5.2.5 on 2025-10-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_delete_tarjetacobro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaBancaria',
        ),
    ]
