# Generated by Django 5.2.5 on 2025-10-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_delete_cuentabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('alias_cbu', models.CharField(max_length=50, verbose_name='Alias/CBU')),
                ('entidad', models.ForeignKey(limit_choices_to={'tipo': 'banco'}, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='webapp.mediopago', verbose_name='Medio de Pago')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuentas_bancarias',
            },
        ),
    ]
