# Generated by Django 5.2.5 on 2025-10-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_cuentabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediocobro',
            name='tipo',
            field=models.CharField(choices=[('tauser', 'Tauser'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria')], max_length=20, verbose_name='Tipo de Método de Cobro'),
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='tipo_cobro',
            field=models.ForeignKey(blank=True, help_text='Configuración global de activación y comisión', null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tipocobro', verbose_name='Tipo de Cobro Global'),
        ),
    ]
