# Generated by Django 5.2.5 on 2025-10-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_alter_mediocobro_tipo_alter_mediocobro_tipo_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
