# Generated by Django 5.2.5 on 2025-10-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_cliente_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(choices=[('tarjeta_nacional', 'Tarjeta de Débito/Crédito Nacional'), ('tarjeta_internacional', 'Tarjeta de Débito/Crédito Internacional (Stripe)'), ('billetera', 'Billetera Electrónica'), ('cuenta_bancaria', 'Cuenta Bancaria')], max_length=30, verbose_name='Tipo de Medio de Pago'),
        ),
        migrations.CreateModel(
            name='TarjetaInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=100, verbose_name='ID de Payment Method en Stripe')),
                ('ultimos_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('exp_month', models.PositiveSmallIntegerField(verbose_name='Mes de Vencimiento')),
                ('exp_year', models.PositiveSmallIntegerField(verbose_name='Año de Vencimiento')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_internacional', to='webapp.mediopago', verbose_name='Medio de Pago')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tarjeta Internacional',
                'verbose_name_plural': 'Tarjetas Internacionales',
                'db_table': 'tarjetas_internacionales',
            },
        ),
        migrations.CreateModel(
            name='TarjetaNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tokenizado', models.CharField(max_length=50, verbose_name='Número Tokenizado')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('ultimos_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('entidad', models.ForeignKey(limit_choices_to={'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.entidad', verbose_name='Banco Emisor')),
                ('medio_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_nacional', to='webapp.mediopago', verbose_name='Medio de Pago')),
                ('moneda', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tarjeta Nacional',
                'verbose_name_plural': 'Tarjetas Nacionales',
                'db_table': 'tarjetas_nacionales',
            },
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
