# Generated by Django 5.2.5 on 2025-10-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_alter_mediopago_tipo_tarjetainternacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetainternacional',
            name='moneda',
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='moneda',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.currency', verbose_name='Moneda'),
        ),
    ]
