# Generated by Django 5.2.5 on 2025-10-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_remove_tarjetainternacional_moneda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetainternacional',
            options={'verbose_name': 'Tarjetas Internacionales', 'verbose_name_plural': 'Tarjetas Internacionales'},
        ),
    ]
