# Generated by Django 5.2.5 on 2025-10-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_alter_tarjetainternacional_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_admin_panel', 'Can access admin panel'), ('access_analyst_panel', 'Can access analyst panel')]},
        ),
    ]
