# Generated by Django 5.2.5 on 2025-10-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_alter_tarjetainternacional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de PaymentIntent en Stripe'),
        ),
    ]
