# Generated by Django 5.2.5 on 2025-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_transaccion_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada por el cliente'), ('COMPLETA', 'Transacción finalizada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10),
        ),
    ]
