# Generated by Django 5.2.5 on 2025-10-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_destino',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_origen',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
