# Generated by Django 5.2.5 on 2025-10-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0061_mfacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='id_transferencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de transferencia'),
        ),
    ]
