# Generated by Django 5.2.5 on 2025-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0062_transaccion_id_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
