# Generated by Django 5.2.5 on 2025-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_alter_transaccion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailscheduleconfig',
            name='weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10, null=True),
        ),
    ]
