# Generated by Django 5.2.5 on 2025-10-20 00:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_emailscheduleconfig_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteIntercambioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_dia_max', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=23, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Límite Diario (Máx.)')),
                ('limite_mes_max', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=23, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Límite Mensual (Máx.)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_config', to='webapp.categoria', verbose_name='Categoría')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_config_por_moneda', to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Config. Límite de Intercambio (Categoría)',
                'verbose_name_plural': 'Config. Límites de Intercambio (Categoría)',
                'ordering': ['categoria__id', 'moneda__code'],
            },
        ),
        migrations.CreateModel(
            name='LimiteIntercambioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_dia_actual', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=23, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Límite Diario (Actual)')),
                ('limite_mes_actual', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=23, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Límite Mensual (Actual)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_cliente', to='webapp.cliente', verbose_name='Cliente')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_por_cliente', to='webapp.limiteintercambioconfig', verbose_name='Configuración de límite (Categoría + Moneda)')),
            ],
            options={
                'verbose_name': 'Límite de Intercambio (Cliente)',
                'verbose_name_plural': 'Límites de Intercambio (Cliente)',
                'ordering': ['cliente__id'],
            },
        ),
        migrations.CreateModel(
            name='LimiteIntercambioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_descontado', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_log', to='webapp.transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='LimiteIntercambioScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual')], default='daily', max_length=20)),
                ('hour', models.PositiveSmallIntegerField(default=0)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('month_day', models.PositiveSmallIntegerField(blank=True, help_text="Día del mes (1–31). Solo si frequency='monthly'.", null=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_intercambio_schedule', to='webapp.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.DeleteModel(
            name='LimiteIntercambio',
        ),
        migrations.AddConstraint(
            model_name='limiteintercambioconfig',
            constraint=models.UniqueConstraint(fields=('categoria', 'moneda'), name='uniq_limite_config_categoria_moneda'),
        ),
        migrations.AddConstraint(
            model_name='limiteintercambiocliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'config'), name='uniq_limite_cliente_config'),
        ),
    ]
