# Generated by Django 5.2.5 on 2025-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0065_limiteintercambioconfig_limiteintercambiocliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiracionTransaccionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('cuenta_bancaria_negocio', 'Cuenta Bancaria de Negocio'), ('tauser', 'Tauser')], max_length=40, unique=True)),
                ('minutos_expiracion', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='limiteintercambioscheduleconfig',
            options={'verbose_name': 'Temporizador global de reseteo de límites', 'verbose_name_plural': 'Temporizador global de reseteo de límites'},
        ),
        migrations.RemoveField(
            model_name='limiteintercambioscheduleconfig',
            name='categoria',
        ),
        migrations.AddField(
            model_name='limiteintercambioscheduleconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limiteintercambioscheduleconfig',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
