# Generated by Django 5.2.5 on 2025-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_expiraciontransaccionconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteintercambioscheduleconfig',
            name='singleton_key',
        ),
        migrations.AddField(
            model_name='limiteintercambioscheduleconfig',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expiraciontransaccionconfig',
            name='medio',
            field=models.CharField(choices=[('cuenta_bancaria_negocio', 'Transferencia'), ('tauser', 'Tauser')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='limiteintercambioscheduleconfig',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual')], max_length=20, unique=True),
        ),
    ]
