# Generated by Django 5.2.5 on 2025-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_expiraciontransaccionconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiraciontransaccionconfig',
            name='medio',
            field=models.CharField(choices=[('cuenta_bancaria_negocio', 'Transferencia'), ('tauser', 'Tauser')], max_length=40, unique=True),
        ),
    ]
