# Generated by Django 5.2.5 on 2025-10-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0067_alter_expiraciontransaccionconfig_medio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor numérico de la denominación (ej: 100.00)', max_digits=20, verbose_name='Valor')),
                ('type', models.CharField(choices=[('bill', 'Billete'), ('coin', 'Moneda')], default='bill', max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='webapp.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Denominación de Moneda',
                'verbose_name_plural': 'Denominaciones de Moneda',
                'ordering': ['currency', '-value'],
                'unique_together': {('currency', 'value')},
            },
        ),
    ]
