# Generated by Django 5.2.5 on 2025-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0069_currencydenomination'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.CharField(default='001', max_length=3)),
                ('pun', models.CharField(default='003', max_length=3)),
                ('min_num', models.IntegerField(default=151)),
                ('max_num', models.IntegerField(default=200)),
                ('current_num', models.IntegerField(default=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('est', 'pun')},
            },
        ),
    ]
