# Generated by Django 5.2.5 on 2025-10-28 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0070_docsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, help_text='CDC del DE (44 dígitos).', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo dígitos.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='factura',
            name='d_num_doc',
            field=models.CharField(blank=True, help_text='Número de documento (7 dígitos).', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Solo dígitos.', regex='^\\d+$'), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AddField(
            model_name='factura',
            name='de_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del DE en fs_proxy.public.de', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='desc_sifen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='est',
            field=models.CharField(blank=True, help_text='Código de establecimiento (3 dígitos).', max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Solo dígitos.', regex='^\\d+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_sifen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fch_sifen',
            field=models.CharField(blank=True, help_text='Fecha/hora SIFEN según proxy (varchar(20)).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pun',
            field=models.CharField(blank=True, help_text='Punto de expedición (3 dígitos).', max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Solo dígitos.', regex='^\\d+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['de_id'], name='webapp_fact_de_id_808ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cdc'], name='webapp_fact_cdc_0c7a74_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='webapp_fact_estado_624d2e_idx'),
        ),
    ]
