# Generated by Django 5.2.5 on 2025-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0071_factura_cdc_factura_d_num_doc_factura_de_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='factura',
            name='webapp_fact_de_id_808ec2_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='webapp_fact_cdc_0c7a74_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='webapp_fact_estado_624d2e_idx',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cdc',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='desc_sifen',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado_sifen',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fch_sifen',
        ),
        migrations.AlterField(
            model_name='factura',
            name='d_num_doc',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='de_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='est',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='pun',
            field=models.CharField(default='003', max_length=3),
        ),
    ]
