# Generated by Django 5.2.5 on 2025-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0072_remove_factura_webapp_fact_de_id_808ec2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='DocSequence',
        ),
    ]
