# Generated by Django 5.2.5 on 2025-10-31 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0073_synclog_delete_docsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauserCurrencyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad de billetes/monedas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tauser_stocks', to='webapp.currency', verbose_name='Moneda')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tauser_stocks', to='webapp.currencydenomination', verbose_name='Denominación')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='webapp.tauser', verbose_name='Tauser')),
            ],
            options={
                'verbose_name': 'Stock de Tauser',
                'verbose_name_plural': 'Stock de Tausers',
                'ordering': ['tauser', 'currency', '-denomination'],
                'unique_together': {('tauser', 'currency', 'denomination')},
            },
        ),
    ]
