# Generated by Django 5.2.5 on 2025-12-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0074_tausercurrencystock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': [('ver_reportes', 'Puede ver los reportes de la empresa')]},
        ),
    ]
