# Generated by Django 5.2.5 on 2025-12-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0075_alter_transaccion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='desc_cliente',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_cobro_porc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_pago_porc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto_base_moneda',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
    ]
