# Generated by Django 5.2.5 on 2025-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0076_transaccion_desc_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comision_vta_com',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
    ]
