# Generated by Django 5.2.5 on 2025-12-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0077_transaccion_comision_vta_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descuento',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Descuento'),
        ),
    ]
