# Generated by Django 5.2.5 on 2025-12-11 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0078_alter_categoria_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cambio_pendiente',
            field=models.BooleanField(default=False, help_text='Indica si hubo un cambio de cotización que el usuario aún no confirmó.'),
        ),
        migrations.CreateModel(
            name='TransaccionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(default='sistema', help_text='usuario | sistema | tarea | otro', max_length=20)),
                ('tipo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('moneda_origen', models.CharField(max_length=10)),
                ('moneda_destino', models.CharField(max_length=10)),
                ('tasa_cambio', models.DecimalField(decimal_places=8, max_digits=16)),
                ('monto_origen', models.DecimalField(decimal_places=8, max_digits=20)),
                ('monto_destino', models.DecimalField(decimal_places=8, max_digits=20)),
                ('medio_pago_id', models.PositiveIntegerField()),
                ('medio_cobro_id', models.PositiveIntegerField()),
                ('medio_pago_porc', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('medio_cobro_porc', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('desc_cliente', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('monto_base_moneda', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('comision_vta_com', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('fecha_snapshot', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, default='')),
                ('medio_cobro_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('medio_pago_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='webapp.transaccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
